# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('is_published', models.BooleanField(default=True)),
                ('external_id', models.PositiveIntegerField()),
            ],
        ),
    ]
